# Generated by Django 5.2.3 on 2025-07-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
